services:
  - type: web
    name: puppeteer-api
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CHROME_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
